### ISSUE TITLE
1.21.4

### ISSUE THREAD

**Issue by Jaxinz** [LeahPy/ImmersiveThunder#15]
Pleaseeee update to 1.21.4 i genuinely love your mod

**Comment by netcatgirl** [comment]
Heya! I'm glad you like it! :) 
I updated the mod to support 1.21.4

**Comment by Jaxinz** [comment]
> Heya! I'm glad you like it! :) I updated the mod to support 1.21.4

thank you soooooo muchhhh <<<<<33333
