### ISSUE TITLE
Immersive Thunder removes a sound from the game

### ISSUE THREAD

**Issue by pocinhas** [LeahPy/ImmersiveThunder#2]
On vanilla mc, when lighting strikes, 2 different sound are played: entity.lighting_bolt.thunder and entity.lighting_bolt.impact
Using Immersive Thunder, when lighting strikes, a single sound is played: leahs-immersive-thunder:thunder_close/medium/far

Examples:
No mod (using a resource pack that changes how it sounds in vanilla):
https://github.com/LeahPy/ImmersiveThunder/assets/101492556/6c100bb7-5a7e-435f-b7b8-0300abd361f2

With the mod:
https://github.com/LeahPy/ImmersiveThunder/assets/101492556/2707575c-2457-4039-a8d3-e45debd9e1d1

The mod is preventing the entity.lighting_bolt.impact from being played, assuming that you meant to only change and to split the entity.lighting_bolt.thunder sound into those 3 distance variants

**Comment by netcatgirl** [comment]
Oh, I'll look into it! Thanks for letting me know! :)

**Comment by netcatgirl** [comment]
After looking at my notes I took when creating this mod, I remember that I did this on purpose because it sounded better (in my opinion), when not playing the entity.lighting_bolt.impact sound.

**Comment by pocinhas** [comment]
Then may I suggest instead of eliminating the sound completely, you mute it on sounds.json? So the sound event would still play but volume is set to 0, something like:

```
  "entity.lighting_bolt.impact": {
    "replace": true,
    "sounds": [
      {"name":"random/explode1", "volume":0},
      {"name":"random/explode2", "volume":0},
      {"name":"random/explode3", "volume":0},
      {"name":"random/explode4", "volume":0},
			]}

**Comment by netcatgirl** [comment]
Sure! :) But can you tell me why this is a better solution? I'm still new to minecraft modding, so it's important for me to understand the benefits of doing it this way.

**Comment by pocinhas** [comment]
I am no modder but I do think that mods and resource packs are a pretty good go-to to enhance the overall playing experience. I am in the making of a resource pack myself and having a mod that eliminates this one sound event, which I use in my pack, is a big enough dealbreaker for me to not use it, even if I love the actual intention of the developer (you) when they made it. Besides all this, I asked you for this one small "fix" because I still want to somehow add support to my project when used paired with my own

If you were looking for more of a general answer rather than a personal one, I guess that if there's a way to have good Vanilla compatibility without any repercussions or changes to the mod's essence, I don't see why not allow it

Again, absolutely no experience in coding, closest I've ever been is .json, but since you asked me I considered giving you my full thoughts on this
(apologies if my English wasnt 100% on this but I hope you get the point :D)

**Comment by netcatgirl** [comment]
Thank you for the insightful reply! I totally agree with you! I will try to update it in the next few days :)

**Comment by netcatgirl** [comment]
With the [latest release](https://github.com/LeahPy/ImmersiveThunder/releases/tag/v1.2), you are now able to toggle the impact sound using the config file. It also supports [Mod Menu](https://modrinth.com/mod/modmenu) to make it more user-friendly :)

Please let me know if this solution satisfies your needs :)

**Comment by pocinhas** [comment]
Purrrrrfect. Really cool how you added it by default too, changed your mind about that?

Btw you released it "incorrectly" on modrinth. You're only featuring the 1.20.1 file because you released both on the same update instead of making 2 new ones. It is up to you but it is likely that people won't find the 1.19.4 version like this, it is rather hidden: 
![image](https://github.com/LeahPy/ImmersiveThunder/assets/101492556/dd5977a6-958d-4f86-835b-a14c5aec991f)

**Comment by pocinhas** [comment]
Other than that seems like we reached a mutual agreement, loved to help! Wish you the best of luck on your Minecraft modding journey! :D

**Comment by netcatgirl** [comment]
> Btw you released it "incorrectly" on modrinth. You're only featuring the 1.20.1 file because you released both on the same update instead of making 2 new ones. It is up to you but it is likely that people won't find the 1.19.4 version like this, it is rather hidden

Ahh, thanks for letting me know! Changed it now :D

And thanks a bunch! Good luck to you as well! :)
