### ISSUE TITLE
[1.20.1] owo sentry does not state which mod requires owolib

### ISSUE THREAD

**Issue by EnderMelody** [LeahPy/ImmersiveThunder#3]
if you launch the game with this mod the owo sentry pops up saying owo lib is needed but it does not specify which mod (this one) requires it.

**Comment by netcatgirl** [comment]
I'll look into it tomorrow, thanks for letting me know! :)

**Comment by netcatgirl** [comment]
I published a new version replacing owo lib with cloth config, so owo lib is not required anymore.
Please let me know if you encounter any more issues :)

**Comment by EnderMelody** [comment]
works fine on the fabric loader but for some reason this mod specifically doesnt recognize the quilt loaders fabric api version and gives a missmatch version error.
[crash-2023-08-14_14.36.12.8993-quilt_loader.txt](https://github.com/LeahPy/ImmersiveThunder/files/12338521/crash-2023-08-14_14.36.12.8993-quilt_loader.txt)

the mod was working fine on quilt before so fixing this error should be fine.

**Comment by netcatgirl** [comment]
Thanks for letting me know! It should work with [this version](https://modrinth.com/mod/immersivethunder/version/1.20.1+1.2.1) :)
Please let me know if it doesn't.

**Comment by EnderMelody** [comment]
seems to be working perfectly now, thanks for the updates 😄👍

**Comment by netcatgirl** [comment]
Awesome :D
