### ISSUE TITLE
Configuring the mod in-game crashes the game.

### ISSUE THREAD

**Issue by MagmaSlime123** [LeahPy/ImmersiveThunder#4]
Title, modlist and other info in report.

https://pastebin.com/T2rtueeB

**Comment by netcatgirl** [comment]
I'll look into it! Thanks for letting me know!

**Comment by netcatgirl** [comment]
I published a new version replacing owo lib with cloth config, which should fix the problem. 
Please let me know if you encounter any more issues :)

**Comment by MagmaSlime123** [comment]
Not sure why Owo Lib was needed before. Could've used Cloth Config API, rather then writing an entirely different config system.

**Comment by netcatgirl** [comment]
That was an oversight on my part. I wasn't aware of cloth config's possibilities, but I'm glad I learned something new this way :)

**Comment by MagmaSlime123** [comment]
Yep. Should probably remove Owo Lib from Modrinth since it's kinda unnecessary now.
