### ISSUE TITLE
Quilt compatibility

### ISSUE THREAD

**Issue by piebaker** [LeahPy/ImmersiveThunder#5]
Would be great to have this compatible with quilt! 
With the newest update it now hard-requires fabric, whereas before it was compatible :(

**Comment by netcatgirl** [comment]
I'll look into it! :)

**Comment by netcatgirl** [comment]
[I uploaded a new version which should work with quilt again.](https://modrinth.com/mod/immersivethunder/version/1.20.1+1.2.1)
Fabric API is still required, though. Please let me know if it works for you :)

**Comment by piebaker** [comment]
Working great again! 
Thanks for the quick fix, this is one of my favourite addition mods

**Comment by netcatgirl** [comment]
Thank you! :)
