### ISSUE TITLE
Missing localization in config menu

### ISSUE THREAD

**Issue by woodiertexas** [LeahPy/ImmersiveThunder#6]
How to reproduce:
- Have Mod Menu installed
- Navigate to "Mods" then to "Immersive Thunder"
- Open the config menu and this will show:
![image](https://github.com/LeahPy/ImmersiveThunder/assets/17211100/78396d93-d426-48bc-9d12-8d9ff9aac857)

**Comment by netcatgirl** [comment]
Oh no, how did I miss that D: Thanks for reporting! 
I'll fix it when updating the mod for 1.20.2 (which should be this week) :)

**Comment by netcatgirl** [comment]
Fixed with version [1.2.2](https://github.com/LeahPy/ImmersiveThunder/releases/tag/v1.2.2). Thanks again for reporting! :)
