### ISSUE TITLE
Error when using this mod on a LAN server

### ISSUE THREAD

**Issue by DarkFireNinja** [LeahPy/ImmersiveThunder#7]
When i try to use this mod on a LAN server with my brother who doesn't have the mod installed (he is using Vanilla Minecraft), he gets this error when he tries to join my world:

**Connection Lost

Unsupported (vanilla?) client!
This server requires modded client to join!**

I'm using Quilt Loader on version 1.20.1 of Minecraft.

**Comment by netcatgirl** [comment]
I'll look into that, thanks for letting me know! :)

**Comment by DarkFireNinja** [comment]
@0x4C656168 Thank you for the reply!

**Comment by netcatgirl** [comment]
Heya! Do you have any other mods installed? 
I was able to replicate the issue, but only when "Quilted Fabric API" is installed. Using Fabric API instead worked for me.

**Comment by DarkFireNinja** [comment]
@0x4C656168 Yes, i do have many other mods installed (including Quilted Fabric API since it is needed for the mods that I'm using on Quilt), but i believe this error still occurs even with Immersive Thunder on it's own. Also, It's interesting that you mentioned that you only get this error when using Quilted Fabric API, maybe that is the issue?

**Comment by netcatgirl** [comment]
Could you try replacing QFAPI with Fabric API? I was not able to find a different way to fix this issue :/

**Comment by DarkFireNinja** [comment]
@0x4C656168 I ran the mod using Fabric Loader and Fabric API instead of Quilt Loader and QFAPI, and it did actually work. But sadly, i am using my own Modpack with a lot of client-side mods, and some of them (the mod Effective for example) is only for Quilt. So, i don't think i will change my Modpack to Fabric instead of Quilt because some of the mods that i am using are only for Quilt. Although, I have been talking to the creator of the mod Better Statistics, and he has been attempting to create a mod that will fix this issue with any mod that has this issue, here: https://github.com/TheCSMods/mc-better-stats/issues/102

**Comment by netcatgirl** [comment]
I think you should be able to use the Fabric API with the Quilt Loader. 
So instead of using Fabric Loader + Fabric API, you could use Quilt Loader + Fabric API. 
Just make sure you don't have QFAPI installed anymore.
Have you tried that?

**Comment by DarkFireNinja** [comment]
@0x4C656168 So, I tried to run Quilt Loader with Fabric API, but the game cant run because a few mods require QFAPI to work, such as:

-Customizable Player Models
-Visual Overhaul
-InvMove
-Effective
-Lambda Better Grass

So, unless i remove those mods, sadly QFAPI will be required for me.

**Comment by netcatgirl** [comment]
Hey, sorry for not checking back in. I was not able to find a simple solution for the problem and don't have the time to further investigate. I'm sorry :/
